No longer allow registering multiple applications
chimeraphp/di-symfony pull request #41
Opened 2020-06-02 14:23 UTC by rodrigorigotti

Closes https://github.com/chimeraphp/di-symfony/issues/38

In order to simplify the container generation process, let's stop allowing the registration of multiple apps in a container and stick to a single one.

A side effect of these changes is that we can statically create the XML files for the services created in the compiler passes. We looked into it but we couldn't do it in a time-efficient manner.

2020-06-02 15:05 UTC, lcobucci requested changes
This seems rather incomplete... the code checking whether or not to register a route/http middleware/query handler/command handler/bus middleware needs to be simplified (because it checks if the app is defined and if so if it matches the given app name).

Apart from that, this is not simplifying the service registration by moving things to the XML (as it claims to be).

2020-06-02 15:05 UTC, lcobucci commented on src/Routing/Expressive/RegisterServices.php
>          $container->setDefinition($this->applicationName . '.http', $app);
The service should be named `ApplicationInterface::class` instead.

2020-06-02 15:05 UTC, lcobucci commented on src/Routing/Expressive/RegisterServices.php
> +        }
This check should have happened way earlier.

2020-06-02 15:05 UTC, lcobucci commented on src/Routing/Expressive/RegisterServices.php
> +        $container->setAlias(ApplicationInterface::class, new Alias($this->applicationName . '.http', true));
The alias should be the other way around.

2020-06-12 08:17 UTC, rodrigorigotti commented
@lcobucci Just so you know we haven't got the time to move on with this PR yet. It's not the case for closing this PR (in my understanding) since apparently it's on the right path, so you're free to pick it up, or someone else. 🙂

2020-06-22 08:20 UTC, rdohms commented
Following up on #43

2021-02-07 14:23 UTC, closed without merging